name: chezliyan_cabs
description: A cab management app for Chezliyan Cabs.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.8.3
  image_picker: ^1.0.0
  url_launcher: ^6.1.10
  intl: ^0.18.1
  permission_handler: ^11.3.1
  http: ^1.1.0  
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 21
